### ISSUE TITLE
configuration problem when using CreateBundle alone

### ISSUE THREAD

**Issue by fpiccinali** [symfony-cmf/CreateBundle#130]
I am trying to use CreateBundle only.

I want to edit entity persisted with doctrine.
I have a fresh new project with 2.6.x and i have added deps for "symfony-cmf/create-bundle": "*"

Then i follow the documentation here http://symfony.com/doc/master/cmf/bundles/create/introduction.html#installation Version 1.2
Here is my config.yml
```
cmf_create:
    object_mapper_service_id: ~
    persistence:
        phpcr:
            enabled:      false
            manager_name: ~
            image:
                enabled:          false
                model_class:      ~
                controller_class: Symfony\Cmf\Bundle\CreateBundle\Controller\ImageController
                basepath:         /cms/media
            delete:               false
fos_rest:
    view:
        formats:
            json: true            
```

When i do ```app/console```
```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                                              
  The path "cmf_create.persistence.phpcr.image.model_class" cannot contain an empty value, but got null.
```

If i comment model_class line, the answer become : 
```
 You need to either enable one of the persistence layers or set the cmf_create.object_mapper_service_id option
```

If i enable phpcr, a deps error appear. 

Where can i find a valid configuration for cmf_create ?

I can write a memo in the documentation if you need.
Or edit composer.json to include correct deps.

**Comment by dbu** [comment]
@fpiccinali did that help, did you get things working?

**Comment by fpiccinali** [comment]
@dbu thanks for your help. 
I cowardly abandoned.

**Comment by dbu** [comment]
oh, a pitty. if you are still interested, keep an eye on #135 - the next version of this bundle should have ORM support built-in.
