### ISSUE TITLE
When install out of box create.js not loaded properly and css as well

### ISSUE THREAD

**Issue by Codenator81** [symfony-cmf/CreateBundle#134]
When install Symfony Cmf Standart 1.2 Create Bundle with demo data not work. In console I see errors 
http://weebdo.local/js/create.js not found
http://weebdo.local/js/ckeditor.js
http://weebdo.local/css/06935bc.css

Happy for any help or solutions 

p.s. I can copy this files from demo http://cmf.liip.ch/en to my web/js and web/css but it is solution?

**Comment by dbu** [comment]
hi @Codenator81 , did you follow http://symfony.com/doc/master/cmf/bundles/create/introduction.html#installation and add the composer post-install and post-update? do you get errors when composer is run? it should download the create git repository in CreateBundle/Resources/public/vendor

**Comment by Codenator81** [comment]
In app_dev.php mode everything is ok. This problem in prod mode app.php decause in app.php he looking for js/create.js and js/ckeditor.js in web dir. My be I on windows and I need put no symlink. I check.

**Comment by Codenator81** [comment]
Seeems where problem when app.php is rewriten and link look like http://weebdo.local/demo but not http://weebdo.local/app.php/demo

**Comment by dbu** [comment]
hm, strange. i think @WouterJ once fixed things to run on windows too.

maybe try to delete app/cache/* and then app/console --env=prod cache:clear and app/console --env=prod assets:install and app/console --env=prod assetic:dump

we are using assetic to combine all the js files together.

**Comment by WouterJ** [comment]
Reading this:

 > In app_dev.php mode everything is ok. This problem in prod mode app.php

I don't think Windows is a problem, but instead Assetic is the trouble maker. Since we're using Assetic, you need to dump the assetic files to make them usable in production. See also http://symfony.com/doc/current/cookbook/assetic/asset_management.html#dumping-asset-files

@dbu now I'm in favor to not use assetic. Things should work out of the box imo

**Comment by Codenator81** [comment]
php app/console assetic:dump --env=prod --no-debug solve problem I think need add to installation manual this

**Comment by dbu** [comment]
@Codenator81 indeed, we miss that in the install instructions. thanks for bringing this to our attention. 

i just die a PR to fix the situation https://github.com/symfony-cmf/symfony-cmf-docs/pull/636

@Codenator81 i added notes to the main installation instructions and the CreateBundle bundle chapter. did you see another place where we would need it?

**Comment by Codenator81** [comment]
Great job! Well done.
