### ISSUE TITLE
No RDFa mapping found

### ISSUE THREAD

**Issue by j-hind** [symfony-cmf/CreateBundle#136]
Please I need some help,
I need to test the createBundle so I installed it base on  http://symfony.com/doc/current/cmf/bundles/create/introduction.html
But I had this error : 
An exception has been thrown during the rendering of a template ("No RDFa mapping found for "Blogger\BlogBundle\Entity\Enquiry" (looked for "Blogger.BlogBundle.Entity.Enquiry.xml")") in BloggerBlogBundle:Page:about.html.twig at line 7

I added Enquiry.xml in the entity repository but still not working

**Comment by dbu** [comment]
hi @j-hind look, closely at the exception message: the file needs to have the full namespace with `\` replaced by `.` try naming that file Blogger.BlogBundle.Entity.Enquiry.xml and place it in Resources/rdf-mappings of your bundle.
