### ISSUE TITLE
[RFC] Dispatch some events in RestController

### ISSUE THREAD

**Issue by umpirsky** [symfony-cmf/CreateBundle#137]
Wouldn't it be nice to have some events dispatched in `RestController.updateDocumentAction()`, `RestController.postDocumentAction()` and `RestController.workflowsAction()`?

My use case is that I want new version for each document update, and I guess that good place to call `DocumentManager.checkpoint()` would be in event listeners that listens to this new events. 

Without this, my best bet would be overriding `RestController.postDocumentAction()`, but only class override is not enough, I will need to inject event dispatcher or document manager in order to achieve this. Or maybe I am missing something?

**Comment by lsmith77** [comment]
right now our focus isn't really on expanding this RestController. Instead we are looking to work on a replacement https://github.com/symfony-cmf/ResourceRestBundle

**Comment by umpirsky** [comment]
Thanks for the quick response @lsmith77!

I see, is it planned for 1.3?

**Comment by lsmith77** [comment]
Not sure yet how things will move forward there.
So we would be generally open to a PR to improve things for you however we are not going to try and do bigger changes. So maybe instead of adding events, we can make the extension points and Bundle configuration more flexible?

**Comment by umpirsky** [comment]
@lsmith77 What do you have in mind? I don't see much space for extension in this controller other then dispatching events.

**Comment by dbu** [comment]
i think the most general solution would be to allow you to extend the controller and make CreateBundle use your class instead of the default. then you can raise events or add logic directly in the controller.

if/when we switch to a general REST handler, we probably can't keep BC with it anyways, so adding nice events here would be a false promise.

**Comment by umpirsky** [comment]
@dbu OK, I see, thanks. I will override it probably.
