### ISSUE TITLE
Unable to find file hallo.coffee

### ISSUE THREAD

**Issue by liquorvicar** [symfony-cmf/CreateBundle#138]
I'm getting an 500 http error code in a Sylius app when trying to view a PDF invoice. 
In the logs I see this message:
[2015-05-21 15:53:21] assetic.ERROR: The template "CmfCreateBundle::includejsfiles-hallo-coffee.html.twig" contains an error: Unable to find file "@CmfCreateBundle/Resources/public/vendor/hallo/src/hallo.coffee". 

I certainly can't see a hallo.coffee file anywhere and I know very little about SymfonyCmf and Google has turned up anything. Wondering if anyone had any pointers as to the source of the error?

**Comment by lsmith77** [comment]
can you double check if you followed the documentation on http://symfony.com/doc/master/cmf/bundles/create/introduction.html#installation ?

**Comment by liquorvicar** [comment]
We installed this as part of Sylius (https://github.com/Sylius/Sylius) so we didn't do the installation ourselves. However I have looked over that doc and run assetic:dump and the error has gone away. Thanks for the pointer!
