### ISSUE TITLE
Content loaded in a wrong language

### ISSUE THREAD

**Issue by Bomere** [symfony-cmf/CreateBundle#168]
Hi,

I am faced with an error that I don't understand... 
I use symfony-cmf (+ create-bundle, simple-cms-bundle and menu-bundle) for our site. 
The multi language system is activated and all translations are available in the database.

When I display a page in a language other than the default language it works!

`<div>
    {% createphp cmfMainContent as="rdf" noautotag %}
        <div {{ createphp_attributes(rdf) }}>
            <div {{ createphp_attributes( rdf.body ) }}>{{ createphp_content( rdf.body ) }}</div>
        </div>
    {% endcreatephp %}
    </div>`

But if I put the menu call, the language displayed is always the default one ...

`{{ knp_menu_render
        ('simple/i-vets', { 'template' : 'HomeBundle:Menu:menu_vertical.html.twig', 'currentClass' : 'current', 'route': app.request.get('_route')})
    }}`

It looks like this problem but there was no solution:
[https://stackoverflow.com/questions/39228263/symfony-cmf-menu-translation](url)

I feel that it is related to the document manager who would be reloaded with wrong locale but I 'm perhaps beside the truth ...

- symfony-cmf: V1.3.0

- symfony-cmf/create-bundle: V1.3.0

- symfony-cmf/menu-bundle: V2.0.1

- symfony-cmf/simple-cms-bundle: V1.3.0

Thank you in advance for your help,
Raphaël.

**Comment by dbu** [comment]
are the models you use for the menu translated menu as well?

note that this bundle, as well as simple-cms-bundle are unmaintained, there is not much capacity here to help you.

**Comment by Bomere** [comment]
For me, the model is correct. I'm using the Symfony MenuNode from 'Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr' which is translatable.

I use a listener to filter the menu according to rights and when I display the used locale, it displays the default one (fr) and not the selected locale ...

Do you have an idea or a track?

I'm aware for the bundle create and simple-cms but if I have to do without it, to perform the updates, it will cause a lot of work ...

**Comment by Bomere** [comment]
I think I found a solution. It seems that if the whole menu chain is not translated, the child nodes are displayed in the default language and that also forces the content (you must also add the locale to the route).
It's strange but it solve the error.

Oddly, your comment helped me!

It was almost 3 days that I was looking in the code ... To update or correct this ...

Thank you so much 👍

**Comment by dbu** [comment]
ah, if you use the the SimpleCmsBundle, menu and content are the same model, and only loaded once. when you first load a document, the language is decided. therefore the language needs to be set before anything is loaded. in the cmf sandbox, we use LuneticsLocaleBundle to set the correct locale on the request, and the phpcr-odm bundle sets the language from the request locale if i memory serves me well.
